
# the aoi table (only required if aoi filter is used)
AOI_TABLE=chyf2.aoi

# the flowpath table that is both the source and target of the geometries to update
EFLOWPATH_TABLE=chyf2.eflowpath

# the properties table which has a graph_id associated
# with each flowpath edge; this is used for
# calculating the smooted elevation; not required
# for computing raw elevation
EFLOWPATH_PROPERTIES_TABLE=chyf2.eflowpath_properties

# the geometry column to read and write from
# this should have no srid or geometry type associated with it
# you can add those back after processing
GEOMETRY_COLUMN=geometry

# the srid of the geometry column
SRID=4617

# the cloud optimized geoservice
# for the DEM
COG_PATH=https://canelevation-dem.s3.ca-central-1.amazonaws.com/mrdem-30/mrdem-30-dtm.tif

# the number of threads to use in processing
NUM_THREADS=2

# the size of blocks (in degrees) for computing
# raw elevation
BLOCK_SIZE=0.4

# the target group size for smoothing processing
# if a connected group is larger than this the entire connected
# group will be computed together
SMOOTHING_TARGET_GROUP_SIZE=100000

# the batch size for processing edges when smoothing
# this is for smoothing internal verticies not the graph
SMOOTHING_FLOWPATH_BATCH_SIZE=500


# leave this empty to process everything
# otherwise you can provided a common delimited list of
# aoi short_names to process
# for elevation this will ONLY process edges in these groups
# for smoothing this will process any edge in this group AND
# any part of the stream network that connects to a edge in the group
# example: 08MF001,08MF002
AOI_FILTER=