# This workflow will build chyf processing tools using Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build CHyF Mainstem and Order Tools with Maven

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B -Pstreamorder clean package
    - name: Upload artifact
      run: mkdir staging && cp ${{ github.workspace }}/chyf-streamorder/target/*.zip staging
    - uses: actions/upload-artifact@v2
      with:
        name: chyf-streamorder
        path: staging
